"use client";
import { NavbarDefault } from '@/components/ui/Navbar'
import { Sidebar } from '@/components/ui/Sidebar'
import { useState } from 'react'
import {
  Button,
} from "@material-tailwind/react";

/* const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false)
  return (
    
    <div className='flex relative'>
    <div className={`${isSidebarOpen ? 'absolute lg:static w-full lg:w-fit top-0 left-0 block': 'hidden'} lg:block`}>
    <Sidebar />
    </div>
    <div className='w-full'>
      <NavbarDefault><Button onClick={()=>setIsSidebarOpen(!isSidebarOpen)} className='inline-block lg:hidden'>Open</Button></NavbarDefault>
    content
    </div>
    </div>
  )
}
